# Generated by Django 5.0.3 on 2024-05-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_user_management', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
