# Generated by Django 5.0.3 on 2024-05-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_user_management', '0005_extendedblacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedBlacklistedToken',
        ),
    ]
