# Generated by Django 4.0.10 on 2024-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='mongo_db_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
