# Generated by Django 4.0.10 on 2024-01-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_composition_mongo_db_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='compostion_uuid',
            new_name='composition_uuid',
        ),
    ]
